import ProviderComponent from "@/components/layouts/provider-component";
import "@/styles/tailwind.css";
import { TRPCReactProvider } from "@/trpc/react";
import { Nunito } from "next/font/google";
import "react-perfect-scrollbar/dist/css/styles.css";

export const metadata = {
    title: "Create T3 App",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }],
};
const nunito = Nunito({
    weight: ["400", "500", "600", "700", "800"],
    subsets: ["latin"],
    display: "swap",
    variable: "--font-nunito",
});
export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" className={nunito.variable}>
            <body>
                <ProviderComponent>
                    <TRPCReactProvider>{children}</TRPCReactProvider>
                </ProviderComponent>
            </body>
        </html>
    );
}
